# An example of a Kubernetes configuration for pod deployment.
apiVersion: apps/v1
kind: Deployment
metadata:
  # Cluster name.
  name: ignite-cluster
  namespace: ignite
spec:
  # The initial number of pods to be started by Kubernetes.
  replicas: 2
  selector:
    matchLabels:
      app: ignite
  template:
    metadata:
      labels:
        app: ignite
    spec:
      serviceAccountName: ignite
      terminationGracePeriodSeconds: 60000
      containers:
        # Custom pod name.
      - name: ignite-node
        image: apacheignite/ignite:2.10.0
        env:
        - name: OPTION_LIBS
          value: ignite-kubernetes,ignite-rest-http
        - name: CONFIG_URI
          value: file:///ignite/config/node-configuration.xml
        - name: JVM_OPTS
          value: "-DIGNITE_WAIT_FOR_BACKUPS_ON_SHUTDOWN=true"
          # if you want to provide the license file via URI, uncomment the following 2 lines
#        - name: LICENSE_URI
#          value: http://url_to_license_file
        ports:
        # Ports to open.
        - containerPort: 47100 # communication SPI port
        - containerPort: 47500 # discovery SPI port
        - containerPort: 49112 # dafault JMX port
        - containerPort: 10800 # thin clients/JDBC driver port
        - containerPort: 8080 # REST API
        volumeMounts:
        - mountPath: /ignite/config
          name: config-vol
#  UNCOMMENT below for readiness probe.
#        readinessProbe:
#          httpGet:
#           path: /ignite?cmd=probe
#           port: 8080
#          initialDelaySeconds: 5
#          failureThreshold: 3
#          periodSeconds: 10
#          timeoutSeconds: 10
# UNCOMMENT below for liveness probe.
#        livenessProbe:
#          httpGet:
#           path: /ignite?cmd=version
#           port: 8080
#          initialDelaySeconds: 5
#          failureThreshold: 3
#          periodSeconds: 10
#          timeoutSeconds: 10
# uncomment the following mount path if you want to provide a license
# the license must be mounted under this exact path
#        - mountPath: /opt/ignite/ignite-license.xml
#          subPath: ignite-license.xml
#          name: license-vol
      volumes:
      - name: config-vol
        configMap:
          name: ignite-config
      # uncomment the following volume if you want to provide a license
#      - name: license-vol
#        configMap:
#          name: ignite-license